const NOTE_CREATE = "NOTE_CREATE"
const NOTE_DELETED = "NOTE_DELETED"
const NOTE_CHANGE = "NOTE_CHANGE"
const FILTER_CHANGE = "FILTER_CHANGE"

export { NOTE_CREATE, NOTE_DELETED, NOTE_CHANGE, FILTER_CHANGE }
